name: swift_agents_chat_example
description: Example app for swift_agents.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  swift_agents:
    path: 'C:/Users/Hp/StudioProjects/swift_agents'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
